### ISSUE TITLE
cannot get to specific section from shell using neovim

### ISSUE THREAD

**Issue by quinoa42** [jez/vim-superman#12]
For example,

`usr/bin/vim -c "SuperMan 3 printf"` will open `printf(3)` perfectly,

but `nvim -c "SuperMan 3 printf"` will open `printf(1)`.

However in nvim, `:SuperMan 3 printf` also works correctly.

**Comment by quinoa42** [comment]
I guess It's a problem caused by neovim itself since `nvim -c "Man 3 printf"` also get into `printf(1)`.

**Comment by jez** [comment]
Looks like this has been fixed upstream in Neovim as of neovim/neovim#5656
